-- =============================================================================
-- Plataforma de Gestión de Stock — Simetra Service SA
-- Base de datos: gestion_de_stock
--
-- Ejecutar completo en el SQL Editor de Supabase (proyecto dedicado).
-- NO ejecutar sobre bases de otros sistemas (equipos, checklists, etc.).
-- Idempotente en lo posible: tipos y seeds usan ON CONFLICT / excepciones.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- ENUMS
-- -----------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE public.estado_entidad AS ENUM ('activo', 'inactivo');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.tipo_rol AS ENUM (
    'Administrador',
    'Responsable_Deposito',
    'Vista_Consulta'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.tipo_movimiento AS ENUM (
    'Entrada',
    'Salida',
    'Transferencia'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.tipo_notificacion AS ENUM (
    'Creacion',
    'Eliminacion',
    'Modificacion',
    'Asignacion_Rol',
    'Invitacion',
    'Bienvenida',
    'Ingreso_Plataforma',
    'Recuperacion_Contrasena',
    'Carga_Movimiento'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- -----------------------------------------------------------------------------
-- TABLAS MAESTRAS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.roles (
  id          smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        public.tipo_rol NOT NULL UNIQUE,
  descripcion text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.responsables (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id    uuid UNIQUE REFERENCES auth.users (id) ON DELETE SET NULL,
  nombre          varchar(120) NOT NULL,
  apellido        varchar(120) NOT NULL,
  dni             varchar(20)  NOT NULL UNIQUE,
  email           varchar(255) NOT NULL UNIQUE,
  id_rol          smallint NOT NULL REFERENCES public.roles (id),
  estado          public.estado_entidad NOT NULL DEFAULT 'activo',
  registrado      boolean NOT NULL DEFAULT false,
  invitado_en     timestamptz,
  registrado_en   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.proveedores (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cod_proveedor  varchar(40)  NOT NULL UNIQUE,
  razon_social   varchar(255) NOT NULL,
  estado         public.estado_entidad NOT NULL DEFAULT 'activo',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.depositos (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_responsable  uuid REFERENCES public.responsables (id) ON DELETE SET NULL,
  codigo          varchar(40)  NOT NULL UNIQUE,
  nombre          varchar(160) NOT NULL,
  ubicacion       varchar(255) NOT NULL,
  cant_articulos  integer      NOT NULL DEFAULT 0 CHECK (cant_articulos >= 0),
  costo_total     numeric(18, 2) NOT NULL DEFAULT 0 CHECK (costo_total >= 0),
  estado          public.estado_entidad NOT NULL DEFAULT 'activo',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.familias (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo       varchar(10)  NOT NULL UNIQUE,
  descripcion  varchar(255) NOT NULL,
  estado       public.estado_entidad NOT NULL DEFAULT 'activo',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.grupos (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_familia   uuid NOT NULL REFERENCES public.familias (id) ON DELETE RESTRICT,
  codigo       varchar(20)  NOT NULL,
  descripcion  varchar(255) NOT NULL,
  estado       public.estado_entidad NOT NULL DEFAULT 'activo',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_familia, codigo)
);

CREATE TABLE IF NOT EXISTS public.articulos (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_grupo          uuid REFERENCES public.grupos (id) ON DELETE SET NULL,
  codigo            varchar(40)  NOT NULL UNIQUE,
  nombre            varchar(255) NOT NULL,
  unidad_de_medida  varchar(40)  NOT NULL,
  estado            public.estado_entidad NOT NULL DEFAULT 'activo',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventario_depositos (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_deposito      uuid NOT NULL REFERENCES public.depositos (id) ON DELETE RESTRICT,
  id_articulo      uuid NOT NULL REFERENCES public.articulos (id) ON DELETE RESTRICT,
  cantidad_actual  integer NOT NULL DEFAULT 0,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_deposito, id_articulo)
);

CREATE TABLE IF NOT EXISTS public.costos_articulos (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_articulo     uuid NOT NULL REFERENCES public.articulos (id) ON DELETE RESTRICT,
  fecha           timestamptz NOT NULL DEFAULT now(),
  costo           numeric(18, 4) NOT NULL CHECK (costo >= 0),
  id_responsable  uuid REFERENCES public.responsables (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tipos_movimiento (
  id          smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        public.tipo_movimiento NOT NULL UNIQUE,
  descripcion text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.movimientos (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_tipo              smallint NOT NULL REFERENCES public.tipos_movimiento (id),
  id_responsable       uuid NOT NULL REFERENCES public.responsables (id),
  id_deposito_origen   uuid REFERENCES public.depositos (id),
  id_deposito_destino  uuid REFERENCES public.depositos (id),
  id_proveedor         uuid REFERENCES public.proveedores (id),
  es_devolucion        boolean NOT NULL DEFAULT false,
  motivo               text,
  fecha                timestamptz NOT NULL DEFAULT now(),
  nro_remito           varchar(80) NOT NULL,
  fotos_remito         text[] NOT NULL DEFAULT '{}',
  cant_total_articulos integer NOT NULL DEFAULT 0 CHECK (cant_total_articulos >= 0),
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_movimiento_depositos_distintos
    CHECK (
      id_deposito_origen IS NULL
      OR id_deposito_destino IS NULL
      OR id_deposito_origen <> id_deposito_destino
    )
);

CREATE TABLE IF NOT EXISTS public.movimientos_articulos (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_movimiento  uuid NOT NULL REFERENCES public.movimientos (id) ON DELETE CASCADE,
  id_articulo    uuid NOT NULL REFERENCES public.articulos (id) ON DELETE RESTRICT,
  cantidad       integer NOT NULL CHECK (cantidad > 0),
  observacion    text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tipos_notificacion (
  id          smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        public.tipo_notificacion NOT NULL UNIQUE,
  descripcion text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notificaciones (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_tipo_notificacion  smallint NOT NULL REFERENCES public.tipos_notificacion (id),
  id_responsable        uuid REFERENCES public.responsables (id) ON DELETE SET NULL,
  id_responsable_extra  uuid REFERENCES public.responsables (id) ON DELETE SET NULL,
  tabla_afectada        varchar(80),
  id_valor_ajustado     uuid,
  fecha                 timestamptz NOT NULL DEFAULT now(),
  descripcion           text NOT NULL,
  metadata              jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.notificaciones_leidas (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_notificacion   uuid NOT NULL REFERENCES public.notificaciones (id) ON DELETE CASCADE,
  id_responsable    uuid NOT NULL REFERENCES public.responsables (id) ON DELETE CASCADE,
  leida_en          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_notificacion, id_responsable)
);

-- -----------------------------------------------------------------------------
-- ÍNDICES
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_responsables_rol ON public.responsables (id_rol);
CREATE INDEX IF NOT EXISTS idx_responsables_estado ON public.responsables (estado);
CREATE INDEX IF NOT EXISTS idx_responsables_auth ON public.responsables (auth_user_id);

CREATE INDEX IF NOT EXISTS idx_depositos_responsable ON public.depositos (id_responsable);
CREATE INDEX IF NOT EXISTS idx_depositos_estado ON public.depositos (estado);

CREATE INDEX IF NOT EXISTS idx_grupos_familia ON public.grupos (id_familia);
CREATE INDEX IF NOT EXISTS idx_articulos_grupo ON public.articulos (id_grupo);
CREATE INDEX IF NOT EXISTS idx_articulos_nombre ON public.articulos (nombre);

CREATE INDEX IF NOT EXISTS idx_inventario_deposito ON public.inventario_depositos (id_deposito);
CREATE INDEX IF NOT EXISTS idx_inventario_articulo ON public.inventario_depositos (id_articulo);

CREATE INDEX IF NOT EXISTS idx_costos_articulo_fecha ON public.costos_articulos (id_articulo, fecha DESC);

CREATE INDEX IF NOT EXISTS idx_movimientos_fecha ON public.movimientos (fecha DESC);
CREATE INDEX IF NOT EXISTS idx_movimientos_tipo ON public.movimientos (id_tipo);
CREATE INDEX IF NOT EXISTS idx_movimientos_responsable ON public.movimientos (id_responsable);
CREATE INDEX IF NOT EXISTS idx_movimientos_origen ON public.movimientos (id_deposito_origen);
CREATE INDEX IF NOT EXISTS idx_movimientos_destino ON public.movimientos (id_deposito_destino);

CREATE INDEX IF NOT EXISTS idx_mov_art_movimiento ON public.movimientos_articulos (id_movimiento);
CREATE INDEX IF NOT EXISTS idx_mov_art_articulo ON public.movimientos_articulos (id_articulo);

CREATE INDEX IF NOT EXISTS idx_notif_fecha ON public.notificaciones (fecha DESC);
CREATE INDEX IF NOT EXISTS idx_notif_tipo ON public.notificaciones (id_tipo_notificacion);
CREATE INDEX IF NOT EXISTS idx_notif_responsable ON public.notificaciones (id_responsable);
CREATE INDEX IF NOT EXISTS idx_notif_tabla_valor ON public.notificaciones (tabla_afectada, id_valor_ajustado);

-- -----------------------------------------------------------------------------
-- SEEDS DE CATÁLOGOS
-- -----------------------------------------------------------------------------
INSERT INTO public.roles (id, tipo, descripcion) VALUES
  (1, 'Administrador', 'ABM completo, invitaciones, historial y notificaciones'),
  (2, 'Responsable_Deposito', 'Opera únicamente sobre sus depósitos asignados'),
  (3, 'Vista_Consulta', 'Solo lectura')
ON CONFLICT (id) DO UPDATE SET tipo = EXCLUDED.tipo, descripcion = EXCLUDED.descripcion;

INSERT INTO public.tipos_movimiento (id, tipo, descripcion) VALUES
  (1, 'Entrada', 'Ingreso de mercadería a un depósito'),
  (2, 'Salida', 'Egreso desde un depósito (incluye devoluciones)'),
  (3, 'Transferencia', 'Traspaso interno entre depósitos')
ON CONFLICT (id) DO UPDATE SET tipo = EXCLUDED.tipo, descripcion = EXCLUDED.descripcion;

INSERT INTO public.tipos_notificacion (id, tipo, descripcion) VALUES
  (1, 'Creacion', 'Alta de un registro maestro'),
  (2, 'Eliminacion', 'Borrado lógico de un registro'),
  (3, 'Modificacion', 'Edición de datos'),
  (4, 'Asignacion_Rol', 'Cambio de rol de un responsable'),
  (5, 'Invitacion', 'Envío de mail de invitación'),
  (6, 'Bienvenida', 'El responsable completó su registro'),
  (7, 'Ingreso_Plataforma', 'Ingreso exitoso con nueva contraseña'),
  (8, 'Recuperacion_Contrasena', 'Envío de mail de recuperación'),
  (9, 'Carga_Movimiento', 'Se cargó un movimiento de stock')
ON CONFLICT (id) DO UPDATE SET tipo = EXCLUDED.tipo, descripcion = EXCLUDED.descripcion;

SELECT setval(pg_get_serial_sequence('public.roles', 'id'), (SELECT MAX(id) FROM public.roles));
SELECT setval(pg_get_serial_sequence('public.tipos_movimiento', 'id'), (SELECT MAX(id) FROM public.tipos_movimiento));
SELECT setval(pg_get_serial_sequence('public.tipos_notificacion', 'id'), (SELECT MAX(id) FROM public.tipos_notificacion));

-- -----------------------------------------------------------------------------
-- FUNCIONES AUXILIARES
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_responsable_id_actual()
RETURNS uuid
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
  v_setting text;
BEGIN
  SELECT r.id
    INTO v_id
  FROM public.responsables r
  WHERE r.auth_user_id = auth.uid()
    AND r.estado = 'activo'
  LIMIT 1;

  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  v_setting := nullif(current_setting('app.responsable_id', true), '');
  IF v_setting IS NOT NULL THEN
    RETURN v_setting::uuid;
  END IF;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_es_administrador()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.responsables r
    JOIN public.roles rol ON rol.id = r.id_rol
    WHERE r.auth_user_id = auth.uid()
      AND r.estado = 'activo'
      AND rol.tipo = 'Administrador'
  );
$$;

CREATE OR REPLACE FUNCTION public.fn_depositos_del_responsable(p_responsable uuid DEFAULT NULL)
RETURNS SETOF uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT d.id
  FROM public.depositos d
  WHERE d.estado = 'activo'
    AND d.id_responsable = COALESCE(p_responsable, public.fn_responsable_id_actual());
$$;

CREATE OR REPLACE FUNCTION public.fn_costo_actual_articulo(p_articulo uuid)
RETURNS numeric
LANGUAGE sql
STABLE
AS $$
  SELECT c.costo
  FROM public.costos_articulos c
  WHERE c.id_articulo = p_articulo
  ORDER BY c.fecha DESC, c.created_at DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.fn_recalcular_totales_deposito(p_deposito uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cant integer;
  v_costo numeric(18, 2);
BEGIN
  SELECT
    COALESCE(SUM(i.cantidad_actual), 0),
    COALESCE(SUM(i.cantidad_actual * COALESCE(public.fn_costo_actual_articulo(i.id_articulo), 0)), 0)
  INTO v_cant, v_costo
  FROM public.inventario_depositos i
  WHERE i.id_deposito = p_deposito;

  UPDATE public.depositos
  SET cant_articulos = v_cant,
      costo_total = ROUND(v_costo, 2),
      updated_at = now()
  WHERE id = p_deposito;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_ajustar_inventario(
  p_deposito uuid,
  p_articulo uuid,
  p_delta integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cantidad integer;
BEGIN
  IF p_deposito IS NULL THEN
    RAISE EXCEPTION 'El depósito es obligatorio para ajustar inventario';
  END IF;

  INSERT INTO public.inventario_depositos (id_deposito, id_articulo, cantidad_actual)
  VALUES (p_deposito, p_articulo, p_delta)
  ON CONFLICT (id_deposito, id_articulo)
  DO UPDATE SET
    cantidad_actual = public.inventario_depositos.cantidad_actual + EXCLUDED.cantidad_actual,
    updated_at = now()
  RETURNING cantidad_actual INTO v_cantidad;

  IF v_cantidad < 0 THEN
    RAISE EXCEPTION 'Stock insuficiente en el depósito % para el artículo % (quedaría %)',
      p_deposito, p_articulo, v_cantidad;
  END IF;

  PERFORM public.fn_recalcular_totales_deposito(p_deposito);
END;
$$;

-- -----------------------------------------------------------------------------
-- VALIDACIÓN E INVENTARIO SOBRE MOVIMIENTOS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_validar_movimiento()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tipo public.tipo_movimiento;
BEGIN
  SELECT tipo INTO v_tipo FROM public.tipos_movimiento WHERE id = NEW.id_tipo;

  IF v_tipo IS NULL THEN
    RAISE EXCEPTION 'Tipo de movimiento inválido';
  END IF;

  IF v_tipo = 'Entrada' THEN
    IF NEW.id_deposito_destino IS NULL THEN
      RAISE EXCEPTION 'Una entrada requiere depósito destino';
    END IF;
    NEW.id_deposito_origen := NULL;
  ELSIF v_tipo = 'Salida' THEN
    IF NEW.id_deposito_origen IS NULL THEN
      RAISE EXCEPTION 'Una salida requiere depósito origen';
    END IF;
    IF NEW.es_devolucion AND NEW.id_proveedor IS NULL THEN
      RAISE EXCEPTION 'Una devolución requiere proveedor';
    END IF;
  ELSIF v_tipo = 'Transferencia' THEN
    IF NEW.id_deposito_origen IS NULL OR NEW.id_deposito_destino IS NULL THEN
      RAISE EXCEPTION 'Una transferencia requiere depósito origen y destino';
    END IF;
    NEW.es_devolucion := false;
    NEW.id_proveedor := NULL;
  END IF;

  IF NEW.id_responsable IS NULL THEN
    NEW.id_responsable := public.fn_responsable_id_actual();
  END IF;

  IF NEW.id_responsable IS NULL THEN
    RAISE EXCEPTION 'No se pudo determinar el responsable del movimiento';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_aplicar_movimiento_articulo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_mov public.movimientos%ROWTYPE;
  v_tipo public.tipo_movimiento;
BEGIN
  SELECT * INTO STRICT v_mov FROM public.movimientos WHERE id = NEW.id_movimiento;
  SELECT tipo INTO STRICT v_tipo FROM public.tipos_movimiento WHERE id = v_mov.id_tipo;

  UPDATE public.movimientos
  SET cant_total_articulos = cant_total_articulos + NEW.cantidad
  WHERE id = NEW.id_movimiento;

  IF v_tipo = 'Entrada' THEN
    PERFORM public.fn_ajustar_inventario(v_mov.id_deposito_destino, NEW.id_articulo, NEW.cantidad);

  ELSIF v_tipo = 'Salida' THEN
    PERFORM public.fn_ajustar_inventario(v_mov.id_deposito_origen, NEW.id_articulo, -NEW.cantidad);
    IF COALESCE(v_mov.es_devolucion, false) = false AND v_mov.id_deposito_destino IS NOT NULL THEN
      PERFORM public.fn_ajustar_inventario(v_mov.id_deposito_destino, NEW.id_articulo, NEW.cantidad);
    END IF;

  ELSIF v_tipo = 'Transferencia' THEN
    PERFORM public.fn_ajustar_inventario(v_mov.id_deposito_origen, NEW.id_articulo, -NEW.cantidad);
    PERFORM public.fn_ajustar_inventario(v_mov.id_deposito_destino, NEW.id_articulo, NEW.cantidad);
  END IF;

  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- NOTIFICACIONES AUTOMÁTICAS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_diff_registros(p_old jsonb, p_new jsonb, p_omitir text[])
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_key text;
  v_partes text[] := ARRAY[]::text[];
BEGIN
  FOR v_key IN SELECT jsonb_object_keys(p_new)
  LOOP
    IF v_key = ANY (p_omitir) THEN
      CONTINUE;
    END IF;
    IF (p_old -> v_key) IS DISTINCT FROM (p_new -> v_key) THEN
      v_partes := array_append(
        v_partes,
        format(
          '%s: %s → %s',
          v_key,
          COALESCE(p_old ->> v_key, 'null'),
          COALESCE(p_new ->> v_key, 'null')
        )
      );
    END IF;
  END LOOP;

  RETURN array_to_string(v_partes, '; ');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_insertar_notificacion(
  p_tipo public.tipo_notificacion,
  p_descripcion text,
  p_tabla text DEFAULT NULL,
  p_valor uuid DEFAULT NULL,
  p_responsable uuid DEFAULT NULL,
  p_responsable_extra uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
  v_tipo_id smallint;
BEGIN
  SELECT id INTO v_tipo_id FROM public.tipos_notificacion WHERE tipo = p_tipo;
  IF v_tipo_id IS NULL THEN
    RAISE EXCEPTION 'Tipo de notificación inexistente: %', p_tipo;
  END IF;

  INSERT INTO public.notificaciones (
    id_tipo_notificacion,
    id_responsable,
    id_responsable_extra,
    tabla_afectada,
    id_valor_ajustado,
    descripcion,
    metadata
  ) VALUES (
    v_tipo_id,
    COALESCE(p_responsable, public.fn_responsable_id_actual()),
    p_responsable_extra,
    p_tabla,
    p_valor,
    p_descripcion,
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- Trigger genérico de auditoría (INSERT/UPDATE en maestros).
-- En UPDATE, estado activo→inactivo se trata como Eliminación (borrado lógico).
-- Solo se usa to_jsonb(NEW/OLD) para soportar tablas con columnas distintas.
CREATE OR REPLACE FUNCTION public.fn_trg_notificar_maestro()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_label text;
  v_diff text;
  v_omitir text[] := ARRAY['updated_at', 'created_at', 'invitado_en', 'registrado_en'];
  v_extra uuid;
  v_rol_old text;
  v_rol_new text;
  v_row jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_row := to_jsonb(NEW);
    v_label := COALESCE(
      v_row ->> 'codigo',
      v_row ->> 'cod_proveedor',
      v_row ->> 'nombre',
      v_row ->> 'razon_social',
      v_row ->> 'descripcion',
      v_row ->> 'dni',
      NEW.id::text
    );

    IF TG_TABLE_NAME = 'costos_articulos' THEN
      PERFORM public.fn_insertar_notificacion(
        'Creacion',
        format('Se registró un nuevo costo %s para el artículo %s', NEW.costo, NEW.id_articulo),
        'costos_articulos',
        NEW.id,
        NEW.id_responsable,
        NULL,
        jsonb_build_object('id_articulo', NEW.id_articulo, 'costo', NEW.costo)
      );
    ELSIF TG_TABLE_NAME = 'responsables' THEN
      PERFORM public.fn_insertar_notificacion(
        'Creacion',
        format('Se creó el responsable %s %s (DNI %s)', NEW.nombre, NEW.apellido, NEW.dni),
        'responsables',
        NEW.id,
        public.fn_responsable_id_actual(),
        NEW.id,
        jsonb_build_object('dni', NEW.dni, 'email', NEW.email)
      );
    ELSE
      PERFORM public.fn_insertar_notificacion(
        'Creacion',
        format('Alta en %s: %s', TG_TABLE_NAME, v_label),
        TG_TABLE_NAME,
        NEW.id
      );
    END IF;

    RETURN NEW;
  END IF;

  -- UPDATE
  IF TG_TABLE_NAME = 'responsables' AND OLD.id_rol IS DISTINCT FROM NEW.id_rol THEN
    SELECT tipo::text INTO v_rol_old FROM public.roles WHERE id = OLD.id_rol;
    SELECT tipo::text INTO v_rol_new FROM public.roles WHERE id = NEW.id_rol;
    PERFORM public.fn_insertar_notificacion(
      'Asignacion_Rol',
      format(
        'Se asignó el rol %s al responsable %s %s, que anteriormente tenía el rol %s',
        v_rol_new, NEW.nombre, NEW.apellido, v_rol_old
      ),
      'responsables',
      NEW.id,
      public.fn_responsable_id_actual(),
      NEW.id,
      jsonb_build_object('rol_anterior', v_rol_old, 'rol_nuevo', v_rol_new)
    );
  END IF;

  IF TG_TABLE_NAME = 'responsables' THEN
    v_omitir := v_omitir || ARRAY['id_rol', 'auth_user_id', 'registrado'];
    v_extra := NEW.id;
  END IF;

  IF TG_TABLE_NAME = 'depositos' THEN
    v_omitir := v_omitir || ARRAY['cant_articulos', 'costo_total'];
  END IF;

  IF to_jsonb(OLD) ? 'estado'
     AND (to_jsonb(OLD) ->> 'estado') = 'activo'
     AND (to_jsonb(NEW) ->> 'estado') = 'inactivo' THEN
    v_label := COALESCE(
      to_jsonb(NEW) ->> 'codigo',
      to_jsonb(NEW) ->> 'cod_proveedor',
      to_jsonb(NEW) ->> 'nombre',
      to_jsonb(NEW) ->> 'razon_social',
      to_jsonb(NEW) ->> 'dni',
      NEW.id::text
    );
    PERFORM public.fn_insertar_notificacion(
      'Eliminacion',
      format('Borrado lógico en %s: %s', TG_TABLE_NAME, v_label),
      TG_TABLE_NAME,
      NEW.id,
      public.fn_responsable_id_actual(),
      v_extra
    );
    RETURN NEW;
  END IF;

  v_diff := public.fn_diff_registros(to_jsonb(OLD), to_jsonb(NEW), v_omitir);
  IF v_diff IS NULL OR btrim(v_diff) = '' THEN
    RETURN NEW;
  END IF;

  PERFORM public.fn_insertar_notificacion(
    'Modificacion',
    format('Modificación en %s: %s', TG_TABLE_NAME, v_diff),
    TG_TABLE_NAME,
    NEW.id,
    public.fn_responsable_id_actual(),
    v_extra,
    jsonb_build_object('cambios', v_diff)
  );

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_trg_notificar_movimiento()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_mov public.movimientos%ROWTYPE;
  v_tipo text;
  v_origen text;
  v_destino text;
  v_depositos text;
BEGIN
  -- Relee el movimiento: el trigger es diferido y ya incluye el detalle.
  SELECT * INTO STRICT v_mov FROM public.movimientos WHERE id = NEW.id;
  SELECT tipo::text INTO v_tipo FROM public.tipos_movimiento WHERE id = v_mov.id_tipo;
  SELECT nombre INTO v_origen FROM public.depositos WHERE id = v_mov.id_deposito_origen;
  SELECT nombre INTO v_destino FROM public.depositos WHERE id = v_mov.id_deposito_destino;

  IF v_tipo = 'Entrada' THEN
    v_depositos := COALESCE(v_destino, 'depósito destino');
  ELSE
    v_depositos := format('%s / %s', COALESCE(v_origen, '-'), COALESCE(v_destino, '-'));
  END IF;

  PERFORM public.fn_insertar_notificacion(
    'Carga_Movimiento',
    format(
      'Movimiento %s (%s). Remito %s. Depósitos: %s. Cantidad total: %s. Motivo: %s',
      v_tipo,
      v_mov.fecha,
      v_mov.nro_remito,
      v_depositos,
      v_mov.cant_total_articulos,
      COALESCE(v_mov.motivo, '-')
    ),
    'movimientos',
    v_mov.id,
    v_mov.id_responsable,
    NULL,
    jsonb_build_object(
      'tipo', v_tipo,
      'id_deposito_origen', v_mov.id_deposito_origen,
      'id_deposito_destino', v_mov.id_deposito_destino,
      'id_proveedor', v_mov.id_proveedor,
      'es_devolucion', v_mov.es_devolucion
    )
  );

  RETURN NEW;
END;
$$;

-- Recalcular costo_total de depósitos cuando cambia el precio de un artículo.
CREATE OR REPLACE FUNCTION public.fn_trg_recalcular_depositos_por_costo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_deposito uuid;
BEGIN
  FOR v_deposito IN
    SELECT DISTINCT id_deposito
    FROM public.inventario_depositos
    WHERE id_articulo = NEW.id_articulo
  LOOP
    PERFORM public.fn_recalcular_totales_deposito(v_deposito);
  END LOOP;
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- TRIGGERS updated_at
-- -----------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_responsables_updated_at ON public.responsables;
CREATE TRIGGER trg_responsables_updated_at
  BEFORE UPDATE ON public.responsables
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_proveedores_updated_at ON public.proveedores;
CREATE TRIGGER trg_proveedores_updated_at
  BEFORE UPDATE ON public.proveedores
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_depositos_updated_at ON public.depositos;
CREATE TRIGGER trg_depositos_updated_at
  BEFORE UPDATE ON public.depositos
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_familias_updated_at ON public.familias;
CREATE TRIGGER trg_familias_updated_at
  BEFORE UPDATE ON public.familias
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_grupos_updated_at ON public.grupos;
CREATE TRIGGER trg_grupos_updated_at
  BEFORE UPDATE ON public.grupos
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_articulos_updated_at ON public.articulos;
CREATE TRIGGER trg_articulos_updated_at
  BEFORE UPDATE ON public.articulos
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- TRIGGERS de negocio
-- -----------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_validar_movimiento ON public.movimientos;
CREATE TRIGGER trg_validar_movimiento
  BEFORE INSERT OR UPDATE ON public.movimientos
  FOR EACH ROW EXECUTE FUNCTION public.fn_validar_movimiento();

DROP TRIGGER IF EXISTS trg_aplicar_inventario ON public.movimientos_articulos;
CREATE TRIGGER trg_aplicar_inventario
  AFTER INSERT ON public.movimientos_articulos
  FOR EACH ROW EXECUTE FUNCTION public.fn_aplicar_movimiento_articulo();

DROP TRIGGER IF EXISTS trg_notificar_movimiento ON public.movimientos;
CREATE CONSTRAINT TRIGGER trg_notificar_movimiento
  AFTER INSERT ON public.movimientos
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_movimiento();

DROP TRIGGER IF EXISTS trg_recalc_deposito_costo ON public.costos_articulos;
CREATE TRIGGER trg_recalc_deposito_costo
  AFTER INSERT ON public.costos_articulos
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_recalcular_depositos_por_costo();

-- Auditoría de maestros
DROP TRIGGER IF EXISTS trg_notif_proveedores ON public.proveedores;
CREATE TRIGGER trg_notif_proveedores
  AFTER INSERT OR UPDATE ON public.proveedores
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_responsables ON public.responsables;
CREATE TRIGGER trg_notif_responsables
  AFTER INSERT OR UPDATE ON public.responsables
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_depositos ON public.depositos;
CREATE TRIGGER trg_notif_depositos
  AFTER INSERT OR UPDATE ON public.depositos
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_familias ON public.familias;
CREATE TRIGGER trg_notif_familias
  AFTER INSERT OR UPDATE ON public.familias
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_grupos ON public.grupos;
CREATE TRIGGER trg_notif_grupos
  AFTER INSERT OR UPDATE ON public.grupos
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_articulos ON public.articulos;
CREATE TRIGGER trg_notif_articulos
  AFTER INSERT OR UPDATE ON public.articulos
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

DROP TRIGGER IF EXISTS trg_notif_costos ON public.costos_articulos;
CREATE TRIGGER trg_notif_costos
  AFTER INSERT ON public.costos_articulos
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_notificar_maestro();

-- -----------------------------------------------------------------------------
-- RPCs DE NEGOCIO
-- -----------------------------------------------------------------------------

-- Login por DNI: el cliente resuelve el email y llama a signInWithPassword.
CREATE OR REPLACE FUNCTION public.rpc_email_por_dni(p_dni text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT email
  FROM public.responsables
  WHERE dni = btrim(p_dni)
    AND estado = 'activo'
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_email_por_dni(text) TO anon, authenticated;

-- Eventos de Auth/EmailJS que no pasan por tablas maestras.
CREATE OR REPLACE FUNCTION public.rpc_registrar_evento_auth(
  p_tipo public.tipo_notificacion,
  p_id_responsable_objetivo uuid,
  p_descripcion text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_tipo NOT IN ('Invitacion', 'Bienvenida', 'Ingreso_Plataforma', 'Recuperacion_Contrasena') THEN
    RAISE EXCEPTION 'Tipo de evento de auth no permitido: %', p_tipo;
  END IF;

  RETURN public.fn_insertar_notificacion(
    p_tipo,
    p_descripcion,
    'responsables',
    p_id_responsable_objetivo,
    public.fn_responsable_id_actual(),
    p_id_responsable_objetivo
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_registrar_evento_auth(public.tipo_notificacion, uuid, text)
  TO authenticated, service_role;

-- Alta transaccional de un movimiento + detalle (atomicidad de N artículos).
CREATE OR REPLACE FUNCTION public.rpc_crear_movimiento(
  p_id_tipo smallint,
  p_id_deposito_origen uuid,
  p_id_deposito_destino uuid,
  p_id_proveedor uuid,
  p_es_devolucion boolean,
  p_motivo text,
  p_nro_remito text,
  p_fotos_remito text[],
  p_articulos jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_movimiento_id uuid;
  v_item jsonb;
  v_responsable uuid;
BEGIN
  IF p_articulos IS NULL OR jsonb_typeof(p_articulos) <> 'array' OR jsonb_array_length(p_articulos) = 0 THEN
    RAISE EXCEPTION 'El movimiento debe incluir al menos un artículo';
  END IF;

  v_responsable := public.fn_responsable_id_actual();
  IF v_responsable IS NULL THEN
    RAISE EXCEPTION 'No hay un responsable autenticado para cargar el movimiento';
  END IF;

  INSERT INTO public.movimientos (
    id_tipo,
    id_responsable,
    id_deposito_origen,
    id_deposito_destino,
    id_proveedor,
    es_devolucion,
    motivo,
    nro_remito,
    fotos_remito
  ) VALUES (
    p_id_tipo,
    v_responsable,
    p_id_deposito_origen,
    p_id_deposito_destino,
    p_id_proveedor,
    COALESCE(p_es_devolucion, false),
    p_motivo,
    btrim(p_nro_remito),
    COALESCE(p_fotos_remito, ARRAY[]::text[])
  )
  RETURNING id INTO v_movimiento_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_articulos)
  LOOP
    INSERT INTO public.movimientos_articulos (
      id_movimiento,
      id_articulo,
      cantidad,
      observacion
    ) VALUES (
      v_movimiento_id,
      (v_item ->> 'id_articulo')::uuid,
      (v_item ->> 'cantidad')::integer,
      nullif(v_item ->> 'observacion', '')
    );
  END LOOP;

  RETURN v_movimiento_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_crear_movimiento(
  smallint, uuid, uuid, uuid, boolean, text, text, text[], jsonb
) TO authenticated;

-- Borrado lógico de familia: inactiva grupos y deja artículos sin grupo.
CREATE OR REPLACE FUNCTION public.rpc_eliminar_familia(p_familia uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.fn_es_administrador() THEN
    RAISE EXCEPTION 'Solo un administrador puede eliminar familias';
  END IF;

  UPDATE public.articulos a
  SET id_grupo = NULL
  WHERE a.id_grupo IN (SELECT g.id FROM public.grupos g WHERE g.id_familia = p_familia);

  UPDATE public.grupos
  SET estado = 'inactivo'
  WHERE id_familia = p_familia
    AND estado = 'activo';

  UPDATE public.familias
  SET estado = 'inactivo'
  WHERE id = p_familia
    AND estado = 'activo';
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_eliminar_familia(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.rpc_eliminar_grupo(p_grupo uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.fn_es_administrador() THEN
    RAISE EXCEPTION 'Solo un administrador puede eliminar grupos';
  END IF;

  UPDATE public.articulos
  SET id_grupo = NULL
  WHERE id_grupo = p_grupo;

  UPDATE public.grupos
  SET estado = 'inactivo'
  WHERE id = p_grupo
    AND estado = 'activo';
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_eliminar_grupo(uuid) TO authenticated;

-- -----------------------------------------------------------------------------
-- VISTAS DE CONSULTA
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_articulos_costo_actual AS
SELECT
  a.*,
  g.codigo AS grupo_codigo,
  g.descripcion AS grupo_descripcion,
  f.id AS id_familia,
  f.codigo AS familia_codigo,
  f.descripcion AS familia_descripcion,
  public.fn_costo_actual_articulo(a.id) AS costo_actual
FROM public.articulos a
LEFT JOIN public.grupos g ON g.id = a.id_grupo
LEFT JOIN public.familias f ON f.id = g.id_familia;

CREATE OR REPLACE VIEW public.v_familias_resumen AS
SELECT
  f.id,
  f.codigo,
  f.descripcion,
  f.estado,
  COUNT(DISTINCT g.id) FILTER (WHERE g.estado = 'activo') AS cant_grupos,
  COUNT(DISTINCT a.id) FILTER (WHERE a.estado = 'activo') AS cant_articulos,
  COALESCE(SUM(public.fn_costo_actual_articulo(a.id)) FILTER (WHERE a.estado = 'activo'), 0) AS costo_total
FROM public.familias f
LEFT JOIN public.grupos g ON g.id_familia = f.id
LEFT JOIN public.articulos a ON a.id_grupo = g.id
GROUP BY f.id;

CREATE OR REPLACE VIEW public.v_grupos_resumen AS
SELECT
  g.id,
  g.id_familia,
  g.codigo,
  g.descripcion,
  g.estado,
  COUNT(a.id) FILTER (WHERE a.estado = 'activo') AS cant_articulos,
  COALESCE(SUM(public.fn_costo_actual_articulo(a.id)) FILTER (WHERE a.estado = 'activo'), 0) AS costo_total
FROM public.grupos g
LEFT JOIN public.articulos a ON a.id_grupo = g.id
GROUP BY g.id;

ALTER VIEW public.v_articulos_costo_actual SET (security_invoker = true);
ALTER VIEW public.v_familias_resumen SET (security_invoker = true);
ALTER VIEW public.v_grupos_resumen SET (security_invoker = true);

-- -----------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- -----------------------------------------------------------------------------
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responsables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.depositos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.familias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_depositos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.costos_articulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_movimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_articulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificaciones_leidas ENABLE ROW LEVEL SECURITY;

-- Catálogos de solo lectura para autenticados
DROP POLICY IF EXISTS roles_select ON public.roles;
CREATE POLICY roles_select ON public.roles
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS tipos_movimiento_select ON public.tipos_movimiento;
CREATE POLICY tipos_movimiento_select ON public.tipos_movimiento
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS tipos_notificacion_select ON public.tipos_notificacion;
CREATE POLICY tipos_notificacion_select ON public.tipos_notificacion
  FOR SELECT TO authenticated USING (true);

-- Administrador: acceso total
DROP POLICY IF EXISTS admin_all_responsables ON public.responsables;
CREATE POLICY admin_all_responsables ON public.responsables
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS self_select_responsable ON public.responsables;
CREATE POLICY self_select_responsable ON public.responsables
  FOR SELECT TO authenticated
  USING (auth_user_id = auth.uid() OR public.fn_es_administrador());

DROP POLICY IF EXISTS self_update_responsable ON public.responsables;
CREATE POLICY self_update_responsable ON public.responsables
  FOR UPDATE TO authenticated
  USING (auth_user_id = auth.uid())
  WITH CHECK (auth_user_id = auth.uid());

DROP POLICY IF EXISTS admin_all_proveedores ON public.proveedores;
CREATE POLICY admin_all_proveedores ON public.proveedores
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS deposito_select_responsable ON public.proveedores;
CREATE POLICY deposito_select_proveedores ON public.proveedores
  FOR SELECT TO authenticated
  USING (estado = 'activo');

DROP POLICY IF EXISTS admin_all_depositos ON public.depositos;
CREATE POLICY admin_all_depositos ON public.depositos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS propio_deposito_select ON public.depositos;
CREATE POLICY propio_deposito_select ON public.depositos
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR id_responsable = public.fn_responsable_id_actual()
  );

DROP POLICY IF EXISTS admin_all_familias ON public.familias;
CREATE POLICY admin_all_familias ON public.familias
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS familias_select ON public.familias;
CREATE POLICY familias_select ON public.familias
  FOR SELECT TO authenticated
  USING (estado = 'activo' OR public.fn_es_administrador());

DROP POLICY IF EXISTS admin_all_grupos ON public.grupos;
CREATE POLICY admin_all_grupos ON public.grupos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS grupos_select ON public.grupos;
CREATE POLICY grupos_select ON public.grupos
  FOR SELECT TO authenticated
  USING (estado = 'activo' OR public.fn_es_administrador());

DROP POLICY IF EXISTS admin_all_articulos ON public.articulos;
CREATE POLICY admin_all_articulos ON public.articulos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS articulos_select_deposito ON public.articulos;
CREATE POLICY articulos_select_deposito ON public.articulos
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR EXISTS (
      SELECT 1
      FROM public.inventario_depositos i
      WHERE i.id_articulo = articulos.id
        AND i.id_deposito IN (SELECT public.fn_depositos_del_responsable())
    )
    OR EXISTS (
      SELECT 1 FROM public.roles r
      JOIN public.responsables resp ON resp.id_rol = r.id
      WHERE resp.auth_user_id = auth.uid()
        AND r.tipo = 'Responsable_Deposito'
    )
  );

DROP POLICY IF EXISTS admin_all_inventario ON public.inventario_depositos;
CREATE POLICY admin_all_inventario ON public.inventario_depositos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS inventario_select_propio ON public.inventario_depositos;
CREATE POLICY inventario_select_propio ON public.inventario_depositos
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR id_deposito IN (SELECT public.fn_depositos_del_responsable())
  );

DROP POLICY IF EXISTS admin_all_costos ON public.costos_articulos;
CREATE POLICY admin_all_costos ON public.costos_articulos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS costos_select ON public.costos_articulos;
CREATE POLICY costos_select ON public.costos_articulos
  FOR SELECT TO authenticated
  USING (public.fn_es_administrador());

DROP POLICY IF EXISTS admin_all_movimientos ON public.movimientos;
CREATE POLICY admin_all_movimientos ON public.movimientos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS movimientos_select_propio ON public.movimientos;
CREATE POLICY movimientos_select_propio ON public.movimientos
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR id_deposito_origen IN (SELECT public.fn_depositos_del_responsable())
    OR id_deposito_destino IN (SELECT public.fn_depositos_del_responsable())
  );

DROP POLICY IF EXISTS movimientos_insert_propio ON public.movimientos;
CREATE POLICY movimientos_insert_propio ON public.movimientos
  FOR INSERT TO authenticated
  WITH CHECK (
    public.fn_es_administrador()
    OR id_deposito_origen IN (SELECT public.fn_depositos_del_responsable())
    OR id_deposito_destino IN (SELECT public.fn_depositos_del_responsable())
  );

DROP POLICY IF EXISTS admin_all_mov_art ON public.movimientos_articulos;
CREATE POLICY admin_all_mov_art ON public.movimientos_articulos
  FOR ALL TO authenticated
  USING (public.fn_es_administrador())
  WITH CHECK (public.fn_es_administrador());

DROP POLICY IF EXISTS mov_art_select_propio ON public.movimientos_articulos;
CREATE POLICY mov_art_select_propio ON public.movimientos_articulos
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR EXISTS (
      SELECT 1 FROM public.movimientos m
      WHERE m.id = movimientos_articulos.id_movimiento
        AND (
          m.id_deposito_origen IN (SELECT public.fn_depositos_del_responsable())
          OR m.id_deposito_destino IN (SELECT public.fn_depositos_del_responsable())
        )
    )
  );

DROP POLICY IF EXISTS mov_art_insert_propio ON public.movimientos_articulos;
CREATE POLICY mov_art_insert_propio ON public.movimientos_articulos
  FOR INSERT TO authenticated
  WITH CHECK (
    public.fn_es_administrador()
    OR EXISTS (
      SELECT 1 FROM public.movimientos m
      WHERE m.id = id_movimiento
        AND (
          m.id_deposito_origen IN (SELECT public.fn_depositos_del_responsable())
          OR m.id_deposito_destino IN (SELECT public.fn_depositos_del_responsable())
        )
    )
  );

DROP POLICY IF EXISTS notif_admin_all ON public.notificaciones;
CREATE POLICY notif_admin_all ON public.notificaciones
  FOR SELECT TO authenticated
  USING (
    public.fn_es_administrador()
    OR (
      id_tipo_notificacion = (SELECT id FROM public.tipos_notificacion WHERE tipo = 'Bienvenida')
      AND (id_responsable = public.fn_responsable_id_actual()
           OR id_responsable_extra = public.fn_responsable_id_actual())
    )
    OR (
      id_tipo_notificacion = (SELECT id FROM public.tipos_notificacion WHERE tipo = 'Ingreso_Plataforma')
      AND (id_responsable = public.fn_responsable_id_actual()
           OR id_responsable_extra = public.fn_responsable_id_actual())
    )
    OR (
      id_tipo_notificacion = (SELECT id FROM public.tipos_notificacion WHERE tipo = 'Carga_Movimiento')
      AND (
        public.fn_es_administrador()
        OR (metadata ->> 'id_deposito_origen')::uuid IN (SELECT public.fn_depositos_del_responsable())
        OR (metadata ->> 'id_deposito_destino')::uuid IN (SELECT public.fn_depositos_del_responsable())
      )
    )
  );

DROP POLICY IF EXISTS notif_insert_system ON public.notificaciones;
CREATE POLICY notif_insert_system ON public.notificaciones
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS notif_leidas_own ON public.notificaciones_leidas;
CREATE POLICY notif_leidas_own ON public.notificaciones_leidas
  FOR ALL TO authenticated
  USING (id_responsable = public.fn_responsable_id_actual())
  WITH CHECK (id_responsable = public.fn_responsable_id_actual());

-- -----------------------------------------------------------------------------
-- STORAGE: imágenes de remito
-- -----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('remitos', 'remitos', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS remitos_select ON storage.objects;
CREATE POLICY remitos_select ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'remitos');

DROP POLICY IF EXISTS remitos_insert ON storage.objects;
CREATE POLICY remitos_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'remitos');

DROP POLICY IF EXISTS remitos_update ON storage.objects;
CREATE POLICY remitos_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'remitos')
  WITH CHECK (bucket_id = 'remitos');

-- -----------------------------------------------------------------------------
-- REALTIME (campana de notificaciones)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'notificaciones'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notificaciones;
  END IF;
END $$;
